---
- name: set up lab environment
  hosts: localhost

  vars:
    tomcat_path: "/home/emehlenb/servers/apache-tomcat-9.0.0"
    git_path: "{{ansible_env.HOME}}/Desktop/associate-consultant-enablement-repo/"
    node_path: "{{ansible_env.HOME}}/Desktop/associate-consultant-enablement-repo/lab/lab-web/src/main/webapp/"

  roles:
    - installs
    - gitrepo

  tasks:

    - block:
      # change to get_url module with external WAR
      - name: move WAR to tomcat folders
        copy:
          src: /lab.WAR
          dest: "{{tomcat_path}}/webapps/lab.war"

      ignore_errors: yes


    - block:
      - name: start tomcat
        shell: ". {{tomcat_path}}/bin/catalina.sh start"

      ignore_errors: yes


    - block:
      - name: npm installs
        npm:
          path: "{{node_path}}"
          state: latest

      - name: start node app
        shell: "node {{node_path}}/app.js"

      ignore_errors: yes
