---
- name: ACE setup
  hosts: localhost
  become: true

  vars_prompt:
    - name: "username"
      prompt: "What is your laptop's non-root username?"
      private: no

  vars:
    tomcat_path: "/home/{{username}}/servers/apache-tomcat-9.0.0"
    git_path: "/home/{{username}}/Desktop/associate-consultant-enablement-repo/"
    node_path: "/home/{{username}}/Desktop/associate-consultant-enablement-repo/lab/lab-web/src/main/webapp/"

  roles:
    - installs
    - gitrepo
    - confirm
