---
- name: ACE setup
  hosts: localhost

  vars:
    tomcat_path: "{{ansible_env.HOME}}/servers/apache-tomcat-8.0.37/"
    git_path: "{{ansible_env.HOME}}/Desktop/associate-consultant-enablement-repo/"
    node_path: "{{ansible_env.HOME}}/Desktop/associate-consultant-enablement-repo/lab/lab-web/src/main/webapp/"

  roles:
    - installs
    - gitrepo
    - confirm
